### ISSUE TITLE
Horizon: AttributeError: 'NoneType' object has no attribute 'is_ajax'

### ISSUE THREAD

**Issue by pjt33** [ging/fiware-idm-deprecated#12]
After installing on a new Ubuntu 14.04 LTS VM and launching horizon with `fab horizon.dev_server` I tried to connect to it with lynx. The result was a 500 Internal Error, and horizon produced the following log:

```
UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
WARNING:py.warnings:UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
DEBUG:idm_logger:Creating a new internal keystoneclient connection to http://127.0.0.1:5000/v3.
Unauthorized: The request you have made requires authentication. (HTTP 401)
Traceback (most recent call last):
  File "/home/fiware/idm/horizon/openstack_dashboard/fiware_api/keystone.py", line 815, in get_basic_role
    roles = manager.roles.list()
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/v3/roles.py", line 109, in list
    return super(RoleManager, self).list(**kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/base.py", line 73, in func
    return f(*args, **new_kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/base.py", line 352, in list
    self.collection_key)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/base.py", line 113, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/adapter.py", line 164, in get
    return self.request(url, 'GET', **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/adapter.py", line 200, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/adapter.py", line 89, in request
    return self.session.request(url, method, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/session.py", line 307, in request
    auth_headers = self.get_auth_headers(auth)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/session.py", line 589, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/auth/base.py", line 114, in get_headers
    token = self.get_token(session)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/auth/identity/base.py", line 104, in get_token
    return self.get_access(session).auth_token
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/auth/identity/base.py", line 144, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/auth/identity/v3.py", line 127, in get_auth_ref
    authenticated=False, log=False, **rkwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/session.py", line 488, in post
    return self.request(url, 'POST', **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/home/fiware/idm/horizon/.venv/src/fiwareclient/keystoneclient/session.py", line 389, in request
    raise exceptions.from_response(resp, method, url)
Unauthorized: The request you have made requires authentication. (HTTP 401)
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    self.load_middleware()
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 47, in load_middleware
    mw_instance = mw_class()
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/home/fiware/idm/horizon/.venv/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/fiware/idm/horizon/openstack_dashboard/urls.py", line 36, in <module>
    from openstack_dashboard.dashboards.idm_admin.user_accounts \
  File "/home/fiware/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/views.py", line 28, in <module>
    from openstack_dashboard.dashboards.idm_admin.user_accounts \
  File "/home/fiware/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 199, in <module>
    class UpdateAccountForm(forms.SelfHandlingForm, UserAccountsLogicMixin, fiware_auth.TemplatedEmailMixin):
  File "/home/fiware/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 206, in UpdateAccountForm
    choices=get_account_choices())
  File "/home/fiware/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 176, in get_account_choices
    use_idm_account=True),
  File "/home/fiware/idm/horizon/openstack_dashboard/fiware_api/keystone.py", line 818, in get_basic_role
    exceptions.handle(request)
  File "/home/fiware/idm/horizon/horizon/exceptions.py", line 291, in handle
    messages.error(request, message or fallback)
  File "/home/fiware/idm/horizon/horizon/messages.py", line 83, in error
    fail_silently=fail_silently)
  File "/home/fiware/idm/horizon/horizon/messages.py", line 41, in add_message
    if not horizon_message_already_queued(request, message):
  File "/home/fiware/idm/horizon/horizon/messages.py", line 28, in horizon_message_already_queued
    if request.is_ajax():
AttributeError: 'NoneType' object has no attribute 'is_ajax'
[02/Sep/2015 08:19:52] "GET / HTTP/1.0" 500 59
```

**Comment by garcianavalon** [comment]
Hi,
You are getting a 401 error: Unauthorized: The request you have made requires authentication. (HTTP 401) when Horizon tries to connect to Keystone.

Make sure that:
- You've run the task fab keystone.populate to create all the required elements in the back-end. https://github.com/ging/fi-ware-idm/#steps-to-install-the-idm-using-the-tools
- The admin user configured in Horizon exists in Keystone, and its credentials are correctly configured. By default is username: idm, password: idm. https://github.com/ging/horizon/blob/master/openstack_dashboard/local/local_settings.py.example#L547
- The admin user is enabled

Try login in to Keystone through the API to check everything is correctly set up.
http://docs.openstack.org/developer/keystone/api_curl_examples.html#project-scoped
http://developer.openstack.org/api-ref-identity-v3.html#authenticate

Best regards,
Enrique

**Comment by pjt33** [comment]
Aha. I thought I only skipped `fab keystone.test_data`, but I must have skipped `fab keystone.populate` as well. Thanks.

**Comment by minhtri1990** [comment]
I using last version.
I had set : 
IDM_USER_CREDENTIALS = {
    'username': 'idm',
    'password': 'idm',
    'project': 'idm',
}
OPENSTACK_HOST = "10.30.176.36"
OPENSTACK_KEYSTONE_URL = "http://%s:5000/v3" % OPENSTACK_HOST

Please help me config horizon.
It's error when I go link http://10.30.176.36:8000/:
the screen display :A server error occurred.  Please contact the administrator.

And Log console:
Starting development server at http://10.30.176.36:8000/
Quit the server with CONTROL-C.
UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
WARNING:py.warnings:UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
RemovedInDjango18Warning: XViewMiddleware has been moved to django.contrib.admindocs.middleware.
WARNING:py.warnings:RemovedInDjango18Warning: XViewMiddleware has been moved to django.contrib.admindocs.middleware.
DEBUG:idm_logger:Creating a new internal keystoneclient connection to http://10.30.176.36:5000/v3.
Recoverable error: Service Unavailable (HTTP 503)
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 168, in __call__
    self.load_middleware()
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 46, in load_middleware
    mw_instance = mw_class()
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/middleware/locale.py", line 23, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 367, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/smartcity/Desktop/idm/horizon/.venv/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 361, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/urls.py", line 36, in <module>
    from openstack_dashboard.dashboards.idm_admin.user_accounts \
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/views.py", line 28, in <module>
    from openstack_dashboard.dashboards.idm_admin.user_accounts \
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 195, in <module>
    class UpdateAccountForm(forms.SelfHandlingForm, UserAccountsLogicMixin):
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 202, in UpdateAccountForm
    choices=get_account_choices())
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/dashboards/idm_admin/user_accounts/forms.py", line 172, in get_account_choices
    use_idm_account=True),
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/fiware_api/keystone.py", line 1027, in get_basic_role
    request, basic, lambda req, n: internal_keystoneclient(req).roles.find(name=n), pickle_props=['name'])
  File "/home/smartcity/Desktop/idm/horizon/openstack_dashboard/fiware_api/keystone.py", line 1002, in _get_element_and_cache
    exceptions.handle(request)
  File "/home/smartcity/Desktop/idm/horizon/horizon/exceptions.py", line 324, in handle
    messages.error(request, message or log_entry)
  File "/home/smartcity/Desktop/idm/horizon/horizon/messages.py", line 83, in error
    fail_silently=fail_silently)
  File "/home/smartcity/Desktop/idm/horizon/horizon/messages.py", line 41, in add_message
    if not horizon_message_already_queued(request, message):
  File "/home/smartcity/Desktop/idm/horizon/horizon/messages.py", line 28, in horizon_message_already_queued
    if request.is_ajax():
AttributeError: 'NoneType' object has no attribute 'is_ajax'
[06/Mar/2017 09:51:47] "GET / HTTP/1.1" 500 59

**Comment by federicofdez** [comment]
Hello @minhtri1990 ,

Thanks for writing. Could you please provide the logs in Keystone?

BR

**Comment by federicofdez** [comment]
@minhtri1990 is it already solved?

**Comment by federicofdez** [comment]
@minhtri1990 I'll close the issue now, but feel free to reopen it if you need so!

BR
