### ISSUE TITLE
ImportError : No module named six

### ISSUE THREAD

**Issue by psManu** [ging/fiware-idm-deprecated#89]
Been struggling to install Keyrock several times in a fresh ubuntu 14.0. x64 server vm. Always its failing due to a missing library 'six'. Followed both the step by step guide and the automated script with no luck. Each time it's missing six 
There's an existing six==1.5.2 in global pip list. in keystone-venv six==1.9.0 and none in horizon  
With scipt Keystone api starts in ports 5000 and 35357 successfully.
But horizon doesn't start at 8000. Tried starting it by sudo service <> start. But it doesn't.

Collecting pyScss==1.2.1 (from -r /home/keyrock/horizon/requirements.txt (line 31))
  Downloading pyScss-1.2.1.tar.gz (95kB)
    100% |████████████████████████████████| 102kB 405kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-YiAYrD/pyScss/setup.py", line 13, in <module>
        from scss.scss_meta import PROJECT, URL, VERSION, AUTHOR, AUTHOR_EMAIL, LICENSE, DOWNLOAD_URL
      File "scss/__init__.py", line 57, in <module>
        import six
    ImportError: No module named six

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-YiAYrD/pyScss/
Command "tools/with_venv.sh pip install --upgrade -r /home/keyrock/horizon/requirements.txt -r /home/keyrock/horizon/test-requirements.txt" failed.
None
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
/home/keyrock/keystone/.venv/local/lib/python2.7/site-packages/migrate/changeset/schema.py:129: MigrateDeprecationWarning: Passing a Column object to alter_column is deprecated. Just pass in keyword parameters instead.
  MigrateDeprecationWarning
--2018-01-02 16:39:23--  https://raw.githubusercontent.com/ging/fiware-idm/master/extras/scripts/expect_idm_password
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 339 [text/plain]
Saving to: ‘expect_idm_password’

100%[======================================>] 339         --.-K/s   in 0s

2018-01-02 16:39:24 (22.4 MB/s) - ‘expect_idm_password’ saved [339/339]

spawn sudo tools/with_venv.sh bin/keystone-manage db_sync --populate
Set a password for the idm user. (If you forget it, the password can be changed later using the admin token):
keystone_idm start/running, process 10519
horizon_idm start/running, process 10534

**Comment by jicarretero** [comment]
I found one workaround. When the installation process fails, I manually install six==1.9.0 and I exec again the installation command:
$ sudo tools/with_venv.sh pip install six==1.9.0

And again:
$ sudo python tools/install_venv.py

This time the installation process will finish.

**Comment by psManu** [comment]
Thanks @jicarretero .
Tried that .But couldn't get it up. Switched to using docker image. That works fine

**Comment by atroisi93** [comment]
Hi everyone, I had this trouble too. I solved it activating the virtualenv created by `install_venv.py` and install manually `six` module.
`sudo -H .venv/bin/pip install six==1.9.0`

**Comment by joansrios** [comment]
@sickboy93  after this issue,  i cant enter to the frontend of idm, with this error:

![imagen](https://user-images.githubusercontent.com/20956876/37445565-c762c0e0-27e6-11e8-866f-9d22e19c3480.png)

how you solve this?

**Comment by atroisi93** [comment]
@RiosQ I used only KeyRock, even I had problem with the frontend. 
However, did you try to shutdown the firewall?
